import type { WorkbenchColors } from '#types/workbench-colors';

import { token } from '#tokens';

/** Editor surface: text area, gutters, find, suggest, hover widgets. */
export const editor = {
  'editor.background': token('bg.base'),
  'editor.findMatchBackground': token('border.transparent'),
  'editor.findMatchBorder': token('accent.emphasis'),
  'editor.findMatchHighlightBackground': token('border.transparent'),
  'editor.findMatchHighlightBorder': token('accent.muted'),
  'editor.findRangeHighlightBackground': token('border.transparent'),
  'editor.findRangeHighlightBorder': token('accent.emphasis'),
  'editor.focusedStackFrameHighlightBackground': token('debug.marker'),
  'editor.foldBackground': token('bg.fold'),
  'editor.foreground': token('fg.primary'),
  'editor.hoverHighlightBackground': token('bg.selectionMuted'),
  'editor.inactiveSelectionBackground': token('bg.selection'),
  'editor.lineHighlightBackground': token('bg.raised'),
  'editor.rangeHighlightBackground': token('border.transparent'),
  'editor.selectionBackground': token('bg.selection'),
  'editor.selectionHighlightBackground': token('border.transparent'),
  'editor.selectionHighlightBorder': token('accent.emphasis'),
  'editor.wordHighlightBackground': token('accent.emphasis'),
  'editor.wordHighlightStrongBackground': token('accent.emphasis'),
  'editorBracketMatch.background': token('fg.guide'),
  'editorBracketMatch.border': token('fg.guideStrong'),
  'editorBracketHighlight.foreground1': token('syntax.fg'),
  'editorBracketHighlight.foreground2': token('syntax.fg'),
  'editorBracketHighlight.foreground3': token('syntax.fg'),
  'editorBracketHighlight.foreground4': token('syntax.fg'),
  'editorBracketHighlight.foreground5': token('syntax.fg'),
  'editorBracketHighlight.foreground6': token('syntax.fg'),
  'editorBracketHighlight.unexpectedBracket.foreground': token('syntax.invalid'),
  'editorCodeLens.foreground': token('fg.primary'),
  'editorCursor.foreground': token('accent.default'),
  'editorError.foreground': token('state.error'),
  'editorGutter.addedBackground': token('state.added'),
  'editorGutter.deletedBackground': token('state.deleted'),
  'editorGutter.modifiedBackground': token('state.modified'),
  'editorHoverWidget.background': token('bg.hoverSoft'),
  'editorHoverWidget.border': token('bg.raised'),
  'editorHoverWidget.foreground': token('fg.onDarkMuted'),
  'editorHoverWidget.statusBarBackground': token('bg.widget'),
  'editorIndentGuide.activeBackground': token('bg.sunken'),
  'editorIndentGuide.background': token('fg.guide'),
  'editorLineNumber.activeForeground': token('fg.lineActive'),
  'editorLineNumber.foreground': token('fg.lineInactive'),
  'editorLink.activeForeground': token('accent.default'),
  'editorMarkerNavigation.background': token('bg.widget'),
  'editorMarkerNavigationWarning.background': token('accent.default'),
  'editorOverviewRuler.addedForeground': token('state.added'),
  'editorOverviewRuler.background': token('bg.base'),
  'editorOverviewRuler.border': token('border.transparent'),
  'editorOverviewRuler.currentContentForeground': token('fg.guide'),
  'editorOverviewRuler.deletedForeground': token('state.deleted'),
  'editorOverviewRuler.errorForeground': token('state.error'),
  'editorOverviewRuler.findMatchForeground': token('accent.muted'),
  'editorOverviewRuler.modifiedForeground': token('state.modified'),
  'editorOverviewRuler.selectionHighlightForeground': token('accent.muted'),
  'editorOverviewRuler.warningForeground': token('accent.default'),
  'editorRuler.foreground': token('fg.guide'),
  'editorSuggestWidget.background': token('bg.raised'),
  'editorSuggestWidget.border': token('bg.raised'),
  'editorSuggestWidget.foreground': token('fg.primary'),
  'editorSuggestWidget.highlightForeground': token('accent.default'),
  'editorSuggestWidget.selectedBackground': token('bg.selectionMuted'),
  'editorWarning.foreground': token('accent.default'),
  'editorWhitespace.foreground': token('fg.whitespace'),
  'editorWidget.background': token('bg.widget'),
} as const satisfies WorkbenchColors;
