import type { WorkbenchColors } from '#types/workbench-colors';

import { token } from '#tokens';

/** Side bar, bottom panel, peek views, editor groups. */
export const panels = {
  'editorGroup.border': token('bg.raised'),
  'editorGroup.dropBackground': token('bg.drop'),
  'editorGroup.emptyBackground': token('bg.widget'),
  'editorGroup.focusedEmptyBorder': token('bg.raised'),
  'editorGroupHeader.border': token('bg.raised'),
  'editorGroupHeader.noTabsBackground': token('bg.base'),
  'editorGroupHeader.tabsBackground': token('bg.base'),
  'editorGroupHeader.tabsBorder': token('bg.raised'),
  'panel.background': token('bg.base'),
  'panel.border': token('bg.raised'),
  'panelInput.border': token('bg.base'),
  'panelSection.border': token('bg.raised'),
  'panelSection.dropBackground': token('bg.drop'),
  'panelSectionHeader.background': token('bg.base'),
  'panelSectionHeader.foreground': token('fg.secondary'),
  'panelTitle.activeBorder': token('accent.default'),
  'panelTitle.activeForeground': token('fg.primary'),
  'panelTitle.inactiveForeground': token('fg.secondary'),
  'peekView.border': token('bg.raised'),
  'peekViewEditor.background': token('bg.widget'),
  'peekViewEditor.matchHighlightBackground': token('accent.soft'),
  'peekViewResult.background': token('bg.widget'),
  'peekViewResult.fileForeground': token('fg.secondary'),
  'peekViewResult.matchHighlightBackground': token('accent.soft'),
  'peekViewTitle.background': token('bg.widget'),
  'peekViewTitleDescription.foreground': token('fg.secondary'),
  'peekViewTitleLabel.foreground': token('fg.secondary'),
  'sash.hoverBorder': token('bg.selection'),
  'sideBar.background': token('bg.base'),
  'sideBar.border': token('bg.raised'),
  'sideBar.dropBackground': token('bg.drop'),
  'sideBar.foreground': token('fg.secondary'),
  'sideBarSectionHeader.background': token('bg.base'),
  'sideBarSectionHeader.border': token('border.subtle'),
  'sideBarSectionHeader.foreground': token('fg.secondary'),
  'sideBarTitle.foreground': token('fg.primary'),
  'walkThrough.embeddedEditorBackground': token('bg.widget'),
} as const satisfies WorkbenchColors;
