import type { WorkbenchColors } from '#types/workbench-colors';

import { token } from '#tokens';

/** Workbench chrome: activity bar, title bar, status bar, tabs. */
export const shell = {
  'activityBar.activeBackground': token('bg.raised'),
  'activityBar.activeBorder': token('accent.default'),
  'activityBar.activeFocusBorder': token('accent.default'),
  'activityBar.background': token('bg.base'),
  'activityBar.border': token('bg.raised'),
  'activityBar.dropBorder': token('accent.emphasis'),
  'activityBar.foreground': token('fg.primary'),
  'activityBar.inactiveForeground': token('fg.secondary'),
  'activityBarBadge.background': token('accent.default'),
  'activityBarBadge.foreground': token('bg.base'),
  'statusBar.background': token('bg.base'),
  'statusBar.border': token('bg.raised'),
  'statusBar.debuggingBackground': token('state.debug'),
  'statusBar.debuggingBorder': token('border.transparent'),
  'statusBar.debuggingForeground': token('bg.base'),
  'statusBar.foreground': token('fg.secondary'),
  'statusBar.noFolderBackground': token('bg.widget'),
  'statusBar.noFolderBorder': token('bg.shadow'),
  'statusBar.noFolderForeground': token('fg.secondary'),
  'statusBarItem.activeBackground': token('bg.sunken'),
  'statusBarItem.errorBackground': token('state.deleted'),
  'statusBarItem.errorForeground': token('fg.primary'),
  'statusBarItem.hoverBackground': token('bg.raised'),
  'statusBarItem.prominentBackground': token('bg.raised'),
  'statusBarItem.prominentForeground': token('bg.hoverSoft'),
  'statusBarItem.prominentHoverBackground': token('bg.overlay'),
  'statusBarItem.remoteBackground': token('bg.hoverSoft'),
  'statusBarItem.remoteForeground': token('fg.primary'),
  'tab.activeBackground': token('bg.sunken'),
  'tab.activeBorder': token('bg.sunken'),
  'tab.activeBorderTop': token('accent.default'),
  'tab.activeForeground': token('fg.primary'),
  'tab.activeModifiedBorder': token('accent.emphasis'),
  'tab.border': token('bg.sunken'),
  'tab.hoverBackground': token('bg.raised'),
  'tab.hoverBorder': token('border.transparent'),
  'tab.hoverForeground': token('fg.primary'),
  'tab.inactiveBackground': token('bg.base'),
  'tab.inactiveForeground': token('fg.secondary'),
  'tab.inactiveModifiedBorder': token('accent.inactive'),
  'tab.unfocusedActiveBackground': token('bg.sunken'),
  'tab.unfocusedActiveBorder': token('border.transparent'),
  'tab.unfocusedActiveBorderTop': token('accent.default'),
  'tab.unfocusedActiveForeground': token('fg.secondary'),
  'tab.unfocusedActiveModifiedBorder': token('accent.inactive'),
  'tab.unfocusedHoverBackground': token('bg.raised'),
  'tab.unfocusedHoverBorder': token('bg.sunken'),
  'tab.unfocusedHoverForeground': token('fg.primary'),
  'tab.unfocusedInactiveBackground': token('bg.base'),
  'tab.unfocusedInactiveForeground': token('fg.secondary'),
  'tab.unfocusedInactiveModifiedBorder': token('accent.inactive'),
  'titleBar.activeBackground': token('bg.base'),
  'titleBar.activeForeground': token('fg.primary'),
  'titleBar.border': token('bg.raised'),
  'titleBar.inactiveBackground': token('bg.base'),
  'titleBar.inactiveForeground': token('fg.secondary'),
  'widget.shadow': token('bg.shadow'),
} as const satisfies WorkbenchColors;
